
# Gopkg.toml example
#
# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md
# for detailed Gopkg.toml documentation.
#
# required = ["github.com/user/thing/cmd/thing"]
# ignored = ["github.com/user/project/pkgX", "bitbucket.org/user/project/pkgA/pkgY"]
#
# [[constraint]]
#   name = "github.com/user/project"
#   version = "1.0.0"
#
# [[constraint]]
#   name = "github.com/user/project2"
#   branch = "dev"
#   source = "github.com/myfork/project2"
#
# [[override]]
#  name = "github.com/x/y"
#  version = "2.4.0"

[prune]
  unused-packages = true
  non-go = true
  go-tests = true

#
# Kubernetes packages
#

[[constraint]]
  name = "k8s.io/client-go"
  version = "~0.17"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "~0.17"

[[constraint]]
  name = "k8s.io/api"
  version = "~0.17"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "~0.17"

[[constraint]]
  name = "k8s.io/cli-runtime"
  version = "~0.17"

# k8s.io/client-go v0.17 uses v1.1.8
[[override]]
  name = "github.com/json-iterator/go"
  version = "=1.1.8"

# k8s.io/client-go v0.17 uses v1.2.1
[[override]]
  name = "github.com/gogo/protobuf"
  version = "=1.2.1"

#
# Cloud provider packages
#
[[constraint]]
  name = "github.com/aws/aws-sdk-go"
  version = "1.13.12"

[[constraint]]
  name = "github.com/Azure/azure-sdk-for-go"
  version = "~21.4.0"

# k8s.io/client-go kubernetes-1.15.3 uses v11.1.2
[[constraint]]
  name = "github.com/Azure/go-autorest"
  version = "11.1.2"

#
# Third party packages
#
[[constraint]]
  name = "github.com/robfig/cron"
  revision = "df38d32658d8788cd446ba74db4bb5375c4b0cb3"

[[constraint]]
  name = "github.com/gofrs/uuid"
  version = "~3.2.0"

[[constraint]]
  name = "github.com/spf13/afero"
  branch = "master"

[[constraint]]
  name = "github.com/spf13/cobra"
  version = "0.0.3"

[[constraint]]
  name = "github.com/spf13/pflag"
  version = "1.0.2"

[[constraint]]
  name = "github.com/stretchr/testify"
  version = "~1.2.2"

[[constraint]]
  name = "github.com/hashicorp/go-plugin"
  revision = "a1bc61569a26c0f65865932c0d55743b0567c494"

# use the version specified by go.mod in the go-plugin repo
# to make future migration to go modules easier
[[override]]
  name = "github.com/hashicorp/go-hclog"
  revision = "ff2cf002a8dd750586d91dddd4470c341f981fe1"

[[constraint]]
  name = "github.com/golang/protobuf"
  version = "~v1.3.1"

[[constraint]]
  name = "google.golang.org/grpc"
  version = "~v1.19.0"

[[constraint]]
  name = "github.com/joho/godotenv"
  version = "~v1.3.0"

[[constraint]]
  name = "github.com/gobwas/glob"
  version = "~v0.2.3"

[[override]]
  name = "golang.org/x/sys"
  branch = "master"

[[constraint]]
  name = "github.com/prometheus/client_golang"
  version = "~1.0"

# needed by the prometheus golang client
[[override]]
  name = "github.com/prometheus/procfs"
  version = "=0.0.2"
